#! /bin/bash

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

CURL='/usr/bin/curl'
ADDR="http://127.0.0.1:8803"

addUser ()
{
    # printf "Type [password]: "
    # read GRANTTYPE

    printf "Username: "
    read USERNAME

    printf "Password: "
    read PWD

    content="$(curl -H 'Content-Type: application/x-www-form-urlencoded' -H 'Authorization: Basic' --form 'grant_type=password&username=${USERNAME}&password=${PWD}' $ADDR/oauth/token)"

    echo "$content"
    exit 0
}

case "$1" in
    addUser)
        addUser
        ;;
    status)
            status_of_proc "$NODEJS" "$NAME" && exit 0 || exit $?
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "oauth -help" >&2
        exit 3
    ;;
esac

exit 0
